name: link_preview
description: Flutter plugin Rich Link Preview, enabling Android and iOS, with customs component like WhatApp Link Preview, Telegram Link Preview, Skype Link Preview, Twitter Link Preview, LinkedIn Link Preview.
version: 0.0.1
author: Denny Segura <dev.dennysegura@gmail.com>
homepage: https://github.com/devdennysegura/flutter-link-preview

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.linkpreview
    pluginClass: LinkPreviewPlugin